project_id = "ncdzzczhjxkyjimkrgub"

[functions.scrape-reddit]
verify_jwt = false

[functions.scrape-reddit-bulk]
verify_jwt = false

[functions.scrape-reddit-scheduled]
verify_jwt = false

[functions.generate-keywords]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false
timeout = 300

[functions.scrape-papers]
verify_jwt = false
